name: Caller Workflow

on: [push]

jobs:
  call-reusable-workflow:
    uses: sujithq/stunning-umbrella/.github/workflows/reusable-workflow.yml@main
    secrets:
      SECRET_NAME: ${{ secrets.SECRET_NAME }}
